image:
  file: .gitpod.Containerfile

tasks:
  - name: SHELL
    init: |
      java --version
      mvn --version
      quarkus --version
      aws --version
      echo "GitPod init at $(date)"
    command:
      echo "GitPod command at $(date)"

ports:
  # DB
  - port: 5432
    onOpen: ignore
    visibility: public
    
  # PROXY
  - port: 9999
    onOpen: ignore
    visibility: public
  
  # WEB
  - port: 8080
    onOpen: ignore
    visibility: public

  - port: 9090
    onOpen: ignore
    visibility: public

  # API
  - port: 9001
    onOpen: ignore
    visibility: public

  # OTHER MODULES
  # - port: 900X
  #  onOpen: ignore
  #  visibility: public

  # Debugger
  - port: 5005
    onOpen: ignore
    visibility: private
  
  # OTHERS PORTS
  - port: 24000
    onOpen: ignore
    visibility: private

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
    - redhat.java
    - esbenp.prettier-vscode
    - svelte.svelte-vscode
    - ms-vscode.vscode-typescript-next

#additionalRepositories:
#
#  - url: https://github.com/CaravanaCloud/PROJECT-secrets